### ISSUE TITLE
Run Time Error 

### ISSUE THREAD

**Issue by karopass** [aritraroy/PinLockView#10]
I am trying to implement Your library as sample application but its getting crashed with run time error.

`@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mPinLockView = (PinLockView) findViewById(R.id.pin_lock_view);
        mPinLockView.setPinLockListener(mPinLockListener);
    }
}
`

I have used code like above....Its giving me error on mPinLockListener.

Thanks

**Comment by aritraroy** [comment]
Please post your XML layout for further investigation.
