### ISSUE TITLE
the number 4 is not visible.

### ISSUE THREAD

**Issue by cwpark** [aritraroy/PinLockView#11]
first of all, thank you for your library!

the PinLockView does not visible number 4 my LG G3.Cat6 device.
i think, can you solve it with little edit to PinLockAdapter.

please see below lines(PinLockAdapter.java: 70):

``` java
if (position == 10) {
  holder.mNumberButton.setText("0");
} else if (position == 9) {
  holder.mNumberButton.setVisibility(View.INVISIBLE);
} else {
  holder.mNumberButton.setText(String.valueOf((position + 1) % 10));
}
```

edit to:

``` java
if (position == 10) {
  holder.mNumberButton.setText("0");
  holder.mNumberButton.setVisibility(View.VISIBLE);
} else if (position == 9) {
  holder.mNumberButton.setVisibility(View.INVISIBLE);
} else {
  holder.mNumberButton.setText(String.valueOf((position + 1) % 10));
  holder.mNumberButton.setVisibility(View.VISIBLE);
}
```

how think about it?

**Comment by aritraroy** [comment]
I didn't experience the problem before. Does this solve the problem for you? Can you post a screenshot of the problem?

**Comment by peter9teufel** [comment]
i have the same issue

The delete button is not shown properly, so I manually called setShowDeleteButton() based on the currently entered pin length ,doing so the delete button works fine but when calling setShowDeleteButton() the number 4 button disappears.

**Comment by aritraroy** [comment]
I have implemented your suggestion. Please let me know if this fixes your issue.

**Comment by cwpark** [comment]
OH, I'm so sorry!
I missed your comment because I forgot this issue. T_T
Thanks for fixing the issue!
