### ISSUE TITLE
Change Ripple Background Runtime

### ISSUE THREAD

**Issue by GauravCreed** [aritraroy/PinLockView#12]
Hi @aritraroy 

it is possible to change the color of ripple effect on click at run time, if yes then how? please help to solve this issue.

**XML UI Like : **

`  <com.andrognito.pinlockview.PinLockView
            android:id="@+id/pin_lock_view"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/indicator_dots"
            android:layout_centerHorizontal="true"
            android:layout_margin="16dp"
            app:keypadButtonSize="72dp"
            app:keypadDeleteButtonDrawable="@drawable/ic_backspace"
            app:keypadDeleteButtonSize="30dp"
            app:keypadShowDeleteButton="true"
            app:keypadTextColor="@color/white"
            app:keypadTextSize="26dp" />`

Thanks.

**Comment by aritraroy** [comment]
Currently the library used default system ripple, so it is not possible to change the color of the ripple dynamically. But this feature can be added if really necessary.
