### ISSUE TITLE
Can't change IndicatorDots colors

### ISSUE THREAD

**Issue by KhalidElSayed** [aritraroy/PinLockView#17]
I can't change the color of empty or filled state of the IndicatorDots neither using "dotEmptyBackground" nor "dotFilledBackground"

**Comment by aritraroy** [comment]
All you need to do is pass a drawable to these attributes and the drawables can have any color as you want. There is nothing that I need to change here to make it possible to color them. You can easily color them using any drawable and putting a color to it.

**Comment by DFreds** [comment]
I'm having the same problem. It is simply ignoring anything I'm passing in. I recommend this be reopened.

My XML is as follows:
```   
<com.andrognito.pinlockview.IndicatorDots
        android:id="@+id/indicator_dots"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/pin_header"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="@dimen/indicator_dots_top_margin" />

<com.andrognito.pinlockview.PinLockView
        android:id="@+id/pin_lock_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/indicator_dots"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="@dimen/keypad_top_margin"
        app:dotFilledBackground="@drawable/my_dot_filled"
        app:indicatorType="fillWithAnimation"
        app:keypadButtonSize="@dimen/keypad_button_size"
        app:keypadShowDeleteButton="true"
        app:keypadTextColor="@color/white"
        app:keypadTextSize="@dimen/keypad_text_size" />
```

my_dot_filled xml is here:

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@color/colorPrimary" />
</shape>
```

**Comment by DFreds** [comment]
They are appearing as normal as if I was not trying to customize them.

**Comment by DFreds** [comment]
Nevermind, it seems that auto-complete is suggesting I put it in the PinLockView, when it really belongs in the IndicatorDots view. Not sure why it would do that.
