### ISSUE TITLE
how to implement ripple effect on pressed

### ISSUE THREAD

**Issue by altaf2892** [aritraroy/PinLockView#18]
>`
    <com.andrognito.pinlockview.IndicatorDots

        android:id="@+id/indicator_dots"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/profile_name"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="36dp"
        app:dotDiameter="12dp"
        app:dotSpacing="16dp" />

    <com.andrognito.pinlockview.PinLockView
        android:id="@+id/pin_lock_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/indicator_dots"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="16dp"
        app:dotFilledBackground="@drawable/dot_filled"
        app:keypadButtonSize="72dp"

        app:keypadDeleteButtonPressedColor="#C8C8C8"
        app:keypadDeleteButtonSize="16dp"
        app:keypadShowDeleteButton="true"
        app:keypadTextColor="@color/white"
        app:keypadTextSize="18dp" />`

**Comment by aritraroy** [comment]
There is already a ripple effect when the buttons are pressed in Lollipop and above. It is not possible to generate ripples natively in pre-lollipop devices. In which API level did you try it?

**Comment by altaf2892** [comment]
sorry for late reply nd yes it works in lollipop and above... thanks
