### ISSUE TITLE
How do you reset mIndicatorDots after PIN # was fully entered?

### ISSUE THREAD

**Issue by Kiarasht** [aritraroy/PinLockView#2]
So if I had the four circles and user entered all four of them, the PIN might be incorrect, and I would like to reset it so they can keep typing instead of erasing it first then typing.

**Comment by aritraroy** [comment]
There is an API available for that, `resetPinLockView()`. This method clears the PIN content internally and updates the indicator dots as well.

You can invoke this method on certain use cases as you wish to.
