### ISSUE TITLE
Last dot for PIN occurs after onComplete?

### ISSUE THREAD

**Issue by Daniel-Wang** [aritraroy/PinLockView#54]
I would like to see the animation of the last dot appear before my onComplete function runs, is that possible?

**Comment by 2mbili** [comment]
Did you find a solution?

**Comment by Daniel-Wang** [comment]
It seems like a work around was the add a few milliseconds delay to the logic that was happening right after the animation, which caused the UI thread to lag.
So that worked.

**Comment by huynguyennovem** [comment]
> It seems like a work around was the add a few milliseconds delay to the logic that was happening right after the animation, which caused the UI thread to lag.
> So that worked.

Can you share your additional code?
