### ISSUE TITLE
Clear indicator dots

### ISSUE THREAD

**Issue by amirj700** [aritraroy/PinLockView#57]
Hi, thanks for your good job. 
I've implemented this in an application and I like to clear indicator dots when the entered pin is incorrect. 
how can I do so?

**Comment by std829** [comment]
you can do `mIndicatorDots.updateDot(0);` or `resetPinLockView();`

**Comment by amirj700** [comment]
thanks for your reply, mPinLockView.resetPinLockView(); works for me now.
