### ISSUE TITLE
Back button isn't being shown

### ISSUE THREAD

**Issue by jd-alexander** [aritraroy/PinLockView#6]
No matter what I do. The back button is not being shown. 

`<com.andrognito.pinlockview.PinLockView
        android:id="@+id/pin_lock_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@id/indicator_dots"
        app:keypadButtonSize="72dp"
        app:keypadTextSize="18dp"
        app:keypadShowDeleteButton="true"
        app:keypadTextColor="@color/white"
        android:layout_centerHorizontal="true"
        android:layout_marginTop="16dp" />
    `

**Comment by jd-alexander** [comment]
Okay i got it to work. Just realized it only appears after entering pin.

**Comment by aritraroy** [comment]
No problem. Keep digging. Let me know if you find any issue.
