### ISSUE TITLE
Allows dots to be initialised as they're being typed

### ISSUE THREAD

**Issue by ProfPh** [aritraroy/PinLockView#7]
Would it be possible to have the indicator dots show up as they're being typed (for a non-fixed PIN length) instead of having the number of dots be the length of the PIN?

**Comment by aritraroy** [comment]
This is a good suggestion. Actually, the indicator was not designed for non-fixed pin lengths. But can be modified easily.

**Comment by jalcine** [comment]
@ProfPh you could do this by setting `app:dotEmptyBackground` to be transparent, no? Unless I'm misunderstanding your intent.

**Comment by aritraroy** [comment]
This has been implemented in version 2.0. Please update and try using the `fill` and `fillWithAnimation` attributes.
