### ISSUE TITLE
Failed to resolve: com.andrognito.pinlockview:pinlockview:2.1.0

### ISSUE THREAD

**Issue by ThreeMinutesFix** [aritraroy/PinLockView#76]
Today when i add the library to my project i receive following error

**
> Failed to resolve: com.andrognito.pinlockview:pinlockview:2.1.0
> Show in Project Structure dialog
> Affected Modules: app

**
Adding screenshot for reference
Version of repo: latest v2.1.0
ss https://ibb.co/XpVJmZh
would be happy if i get immediate solution as i have projects depend on this repo

**Comment by Bieenn01** [comment]
did you fixed it ?

**Comment by Bieenn01** [comment]
i still cant navigate the andrognito.pinlockview on the maven repository
